changes done

diff --git a/.github/workflows/main_frontendapp.yml b/.github/workflows/main_frontendapp.yml
--- a/.github/workflows/main_frontendapp.yml
+++ b/.github/workflows/main_frontendapp.yml
@@ -1,7 +1,7 @@
 # Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
 # More GitHub Actions for Azure: https://github.com/Azure/actions
 
-name: Build and deploy Node.js app to Azure Web App - backendapp
+name: Build and deploy Node.js app to Azure Web App - frontendapp
 
 on:
   push:
@@ -25,21 +25,24 @@ jobs:
 
       - name: npm install, build, and test
         run: |
-          cd server
+          cd client
           npm install
-          npm run build --if-present
+          npm run build || exit 1  # Fail if build fails
           npm run test --if-present || echo "Skipping tests..."
 
       - name: Zip artifact for deployment
         run: |
-          cd server
-          zip -r release.zip ./*
+          cd client
+          ls -la dist  # Debug: Ensure the dist folder exists
+          zip -r release.zip ./dist
+          ls -la  # Debug: Confirm release.zip is created
+
 
       - name: Upload artifact for deployment job
         uses: actions/upload-artifact@v4
         with:
           name: node-app
-          path: server/release.zip
+          path: client/release.zip
 
   deploy:
     runs-on: ubuntu-latest
@@ -61,7 +64,7 @@ jobs:
         id: deploy-to-webapp
         uses: azure/webapps-deploy@v3
         with:
-          app-name: 'backendapp'
+          app-name: 'frontendapp'
           slot-name: 'Production'
-          package: .
-          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BF5650A3DC0C48C2BC62A9F76E977007 }}
+          package: release.zip
+          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_93DAE751F2DD4CE890A483713F05B0C4 }}
